bitsy-ai/octoprint-nanny-plugin

setup.py

As you saw in #19, people are stupid and don't understand that if the plugin manager doesn't show them a plugin, it is because it incompatible.
They also seemingly *never* read the compatibility information. So they try and install it manually....
This sets a minimum Python version (3) so that pip provides a sensible error message.
I made one other change, so that there would not be a syntax error on install if not Python 3 and not supported arch.
*Hopefully* this means that you get less of these issues in the future, since it actually provides a decent error message.

Set minimum Python version

---

setup.py

I totally should have seen this one coming; distributing Raspbian / Raspberry Pi OS with a 32-bit user space will help bridge the software support gap while everyone scrambles to write for 64-bit address space.

64 bit kernel! 32-bit software! oh my!

---

octoprint_nanny/clients/rest.py
octoprint_nanny/manager.py
octoprint_nanny/plugins.py
octoprint_nanny/predictor.py
octoprint_nanny/workers/monitoring.py
octoprint_nanny/workers/mqtt.py

Cloud IoT core charges for bandwidth; instead of sending calibration coordinates/mask on every inference, persist to a database row that can be referencing by DataFlow proc. 
closes #107

Remove calibration from telemetry messages

---

octoprint_nanny/clients/flatbuffers.py
octoprint_nanny/predictor.py
octoprint_nanny/types.py
octoprint_nanny/workers/monitoring.py
setup.py
tests/conftest.py
tests/test_benchmarks.py
tests/workers/test_monitoring.py

Implement Lite mode health score

---

MANIFEST.in
setup.py

New model versions are now sent over the wire via MQTT config update, closes #143

Remove TensorFlow model from package data/manifest

---

octoprint_nanny/plugins.py

Fixes the following error on startup:
2021-04-25 01:51:32,666 - octoprint.plugin - ERROR - Error while calling plugin octoprint_nanny
Traceback (most recent call last):
File "/home/leigh/projects/OctoPrint/.venv/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
result = getattr(plugin, method)(*args, **kwargs)
File "/home/leigh/projects/OctoPrint/.venv/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
return f(*args, **kwargs)
File "/home/leigh/projects/OctoPrint/.venv/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
return f(*args, **kwargs)
File "/home/leigh/projects/octoprint-nanny-plugin/octoprint_nanny/plugins.py", line 611, in on_after_startup
configure_logger(logger, …

Fix error on plugin startup

---

requirements.txt
setup.py

```
octoprint          |   File "/octoprint/plugins/lib/python3.8/site-packages/jwt/api_jws.py", line 115, in encode
octoprint          |     raise NotImplementedError(
octoprint          | NotImplementedError: Algorithm 'ES256' could not be found. Do you have cryptography installed?
```

Fixes exception thrown when cryptography lib is not installed

---

octoprint_nanny/workers/websocket.py

Current behavior:
```
2021-06-01 00:14:59,660 - asyncio - WARNING - socket.send() raised exception.
2021-06-01 00:15:00,761 - asyncio - WARNING - socket.send() raised exception.
2021-06-01 00:15:01,839 - asyncio - WARNING - socket.send() raised exception.
2021-06-01 00:15:02,943 - asyncio - WARNING - socket.send() raised exception.
2021-06-01 00:15:04,034 - asyncio - WARNING - socket.send() raised exception.
```

Wrap coroutine in asyncio.ensure_future() to ensure errors are re-raised

---

octoprint_nanny/clients/protobuf.py
octoprint_nanny/settings.py
octoprint_nanny/workers/mqtt.py
requirements.txt
setup.py
tests/conftest.py

Protobuf's python implementation does not use PyObject init, which was resulting in the following incorrect memory pointers being used
left: protobuf, right: python float
```
2021-06-20 19:25:54,967 - octoprint.plugins.octoprint_nanny.workers.monitoring - INFO - Initialized ws connection
2021-06-20 19:25:56,139 - octoprint.plugins.octoprint_nanny.settings - INFO - Created ts=1624213504.0 from ts=1624213556.137391
2021-06-20 19:25:57,202 - octoprint.plugins.octoprint_nanny.settings - INFO - Created ts=1624213504.0 from ts=1624213557.200458
2021-06-20 19:25:58,306 - octoprint.plugins.octoprint_nanny.settings - INFO - Created ts=1624213504.0 from ts=1624213558.303977
2021-06-20 19:25:59,402 - octoprint.plugins.octoprint_nanny.settings - INFO - Created ts=1624213504.0 from …
```

Fix protobuf pyobject init

---

octoprint_nanny/__init__.py
octoprint_nanny/clients/mqtt.py
octoprint_nanny/manager.py
octoprint_nanny/plugins.py
octoprint_nanny/settings.py
octoprint_nanny/static/js/nanny.js
octoprint_nanny/workers/monitoring.py
octoprint_nanny/workers/mqtt.py
setup.cfg
setup.py

* initialize print session if None set in telemetry payload builder; reset print session on PRINE_DONE PRINT_FAILED PRINT_CANCELLED events
* refer to octoprint environment dict as octoprint_environment everywhere; log device info before upsert
* fix exception in MQTT manager shutdown handler, handle exceptions in publish_octoprint_event_telemetry
* simplify print_session creation and reset
* revert sync build_telemetry_event
* fix mypy

Release v0.7.2

---

octoprint_nanny/static/js/nanny.js
octoprint_nanny/workers/mqtt.py

If something went wrong during MQTT client initialization (network timeout, device registration failed, etc), two fatal exceptions were thrown on subsequent server startup/shutdown. This fixes both.
on startup:
```
2021-07-04 22:16:46,027 - octoprint - ERROR - Error while trying to migrate settings for plugin octoprint_nanny, ignoring it
Traceback (most recent call last):
File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/__init__.py", line 512, in init_settings_plugin_config_migration_and_cleanup
implementation._identifier, implementation
File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/__init__.py", line 506, in settings_plugin_config_migration_and_cleanup
implementation.on_settings_initialized()
File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init_ …
```

MQTT worker graceful startup/shutdown

---

octoprint_nanny/templates/octoprint_nanny_settings_shared.jinja2

Fixes 404 when OctoPrint is served from /octoprint/ path:

use a relative url for PrintNanny banner img

---

octoprint_nanny/templates/octoprint_nanny_settings_shared.jinja2
octoprint_nanny/templates/octoprint_nanny_tab.jinja2

Fixes the following error in the latest nightly + rc1
```
Apr 19 10:11:05 octonanny-04-18 octoprint[451]: Traceback (most recent call last):
Apr 19 10:11:05 octonanny-04-18 octoprint[451]:   File "/home/pi/.octoprint/venv/lib/python3.9/site-packages/octoprint/util/jinja.py", line 255, in _handle_body
Apr 19 10:11:05 octonanny-04-18 octoprint[451]:     return caller()
Apr 19 10:11:05 octonanny-04-18 octoprint[451]:   File "/home/pi/.octoprint/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 763, in __call__
Apr 19 10:11:05 octonanny-04-18 octoprint[451]:     return self._invoke(arguments, autoescape)
Apr 19 10:11:05 octonanny-04-18 octoprint[451]:   File "/home/pi/.octoprint/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
Apr 19 10:11:05 octonanny-04-18 …
```

fix more config accessors in jinja templates

---

octoprint_nanny/plugins.py

Fixes issue where wizard prompts for account link, even if account is already linked. If this doesn't work, might need to read printnanny_config in template vars fn.

initialize settings defaults in fn instead of module scope

---

octoprint_nanny/utils/printnanny_os.py

Applying a swupdate patch updates the root filesystem, which does not include the boot partition. Read from /etc/issue instead.

Read issue.txt from /etc/issue

---

Makefile
octoprint_nanny/plugins.py
octoprint_nanny/utils/printnanny_os.py

The default value is invalid in the latest 0.2.0 build. Should be using a single source of truth (PrintNanny config CLI) instead of trying to set defaults adhoc.

Hotfix: read Janus API url from printnanny config

---

octoprint_nanny/utils/printnanny_os.py

Fixes an error in 0.13.0 production builds:
```
Aug 22 14:56:09 pn-0-3-0 octoprint[736]: 2022-08-22 14:56:09,475 - octoprint.server.api - ERROR - There was an error fetching wizard details for octoprint_nanny, ignoring
Aug 22 14:56:09 pn-0-3-0 octoprint[736]: Traceback (most recent call last):
Aug 22 14:56:09 pn-0-3-0 octoprint[736]:   File "/usr/lib/python3.10/site-packages/octoprint/server/api/__init__.py", line 189, in wizardState
Aug 22 14:56:09 pn-0-3-0 octoprint[736]:     required = implementation.is_wizard_required()
Aug 22 14:56:09 pn-0-3-0 octoprint[736]:   File "/usr/lib/python3.10/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
Aug 22 14:56:09 pn-0-3-0 octoprint[736]:     return f(*args, **kwargs)
Aug 22 14:56:09 pn-0-3-0 octoprint[736]:   File …
```

Fix error: Cannot run the event loop while another loop is running

---

octoprint_nanny/__init__.py
octoprint_nanny/static/js/octo_printnanny.js
setup.cfg
setup.py

An HLS compatibility mode is now provided for OctoPrint, so this warning is no longer needed.
https://github.com/bitsy-ai/printnanny-os/issues/103

Remove octoprint cam warning

---

octoprint_nanny/static/js/octo_printnanny.js

HLS compatibility is now provided in PrintNanny OS v0.4.0, so this warning is no longer needed.

Remove CameraWarningViewModel 

---

octoprint_nanny/utils/printnanny_os.py
setup.py

ref: https://github.com/bitsy-ai/printnanny-os/issues/248

Fix: OctoPrint fails to load PrintNanny Cloud data #248

---

octoprint_nanny/plugins.py

We no longer need this key, so avoid generating it unnecessarily.

Remove global OctoPrint key generation

---

octoprint_nanny/events.py
tests/test_events.py

Publish NATS messages to a subject parameterized by hostname instead of Cloud ID

Remove dependency on Cloud data model id

---

octoprint_nanny/plugins.py

Fixes the following error in the currently nightly:
```
Mar 28 16:39:35 dev-rpi4 octoprint[785]:   File "/usr/lib/python3.10/site-packages/octoprint_nanny/events.py", line 101, in printnanny_nats_print_progress_msg
Mar 28 16:39:35 dev-rpi4 octoprint[785]:     progress = printnanny_octoprint_models.JobProgress(**progress_kwargs)
Mar 28 16:39:35 dev-rpi4 octoprint[785]: TypeError: printnanny_octoprint_models.JobProgress.JobProgress() argument after ** must be a mapping, not int
```

Fix incorrect progress data
