- Makefile
- setup.py
> Install platform dependencies 

- setup.py
> Permit null fields in Printer Profile serializer; bump client >=0.2.3

- Makefile
- setup.py
> release v0.2.3

- README.md
Just fixing the plugin setup page url in the readme
> Setup url fix

- setup.py
> fix aarch64 install logic

- setup.cfg
- setup.py
> Release v0.2.5

- octoprint_nanny/clients/rest.py
- octoprint_nanny/manager.py
- octoprint_nanny/plugins.py
- setup.cfg
- setup.py
* Receive notifications on percentage progress/completion of a print
* Added UI notification system to Print Nanny Webapp (new Vue app)
* Added a TypeScript API client (unpublished)
* Added notification settings and history to Print Nanny Webapp
A more detailed write up is coming in the first ever Print Nanny newsletter!
* fixes #59
* Fixes a bunch exceptions appearing in HoneyComb
> Release v0.3.0

- Makefile
- octoprint_nanny/clients/mqtt.py
- octoprint_nanny/manager.py
- octoprint_nanny/plugins.py
- octoprint_nanny/static/js/nanny.js
- setup.cfg
- setup.py
* Closes #63 
* Gracefully re-initialize worker threads when certain OctoPrint settings stored in thread-local state are changed (device registration and auth token).
> Release v0.3.1

- octoprint_nanny/manager.py
> Handle case where telemetry events endpoint is unavailable

- octoprint_nanny/plugins.py
> fix exception that was returned

- octoprint_nanny/clients/websocket.py
- octoprint_nanny/manager.py
- octoprint_nanny/plugins.py
- octoprint_nanny/predictor.py
- octoprint_nanny/static/js/nanny.js
- octoprint_nanny/templates/octoprint_nanny_settings_shared.jinja2
> Add frames-per-minute setting

- octoprint_nanny/clients/honeycomb.py
- octoprint_nanny/clients/mqtt.py
- octoprint_nanny/clients/rest.py
- octoprint_nanny/clients/websocket.py
- octoprint_nanny/manager.py
- octoprint_nanny/plugins.py
- octoprint_nanny/predictor.py
- tests/test_mqtt.py
- tests/test_websocket.py
> Issue 86 honeycomb traces

- Makefile
- octoprint_nanny/plugins.py
- setup.cfg
- setup.py
> Release v0.4.3

- octoprint_nanny/__init__.py
- octoprint_nanny/manager.py
- octoprint_nanny/plugins.py
- setup.py
> Add file log handler

- octoprint_nanny/exceptions.py
- octoprint_nanny/plugins.py
https://github.com/bitsy-ai/octoprint-nanny-plugin/issues/120
> Verify disk contents against server-provided checksum

- octoprint_nanny/manager.py
- octoprint_nanny/plugins.py
> Sync printer profiles on login

- octoprint_nanny/clients/rest.py
- octoprint_nanny/workers/websocket.py
> Add websocket reconnect

- octoprint_nanny/clients/flatbuffers.py
- octoprint_nanny/clients/mqtt.py
- octoprint_nanny/types.py
- octoprint_nanny/workers/monitoring.py
- octoprint_nanny/workers/mqtt.py
- setup.py
- tests/test_benchmarks.py
- tests/test_manager.py
- tests/workers/test_monitoring.py
> Active learning testing

- octoprint_nanny/clients/flatbuffers.py
- octoprint_nanny/clients/mqtt.py
- octoprint_nanny/manager.py
- octoprint_nanny/plugins.py
- octoprint_nanny/settings.py
- octoprint_nanny/static/js/nanny.js
- octoprint_nanny/templates/octoprint_nanny_settings_shared.jinja2
- octoprint_nanny/types.py
- octoprint_nanny/workers/monitoring.py
- octoprint_nanny/workers/mqtt.py
- tests/conftest.py
- tests/test_manager.py
- tests/workers/test_monitoring.py
> Dataflow testing, part 2

- octoprint_nanny/workers/monitoring.py
- setup.py
https://github.com/bitsy-ai/octoprint-nanny-plugin/issues/108
> Log print session string

- octoprint_nanny/clients/rest.py
- octoprint_nanny/workers/mqtt.py
- setup.py
- tests/test_manager.py
https://github.com/bitsy-ai/octoprint-nanny-plugin/issues/146
> Remove concept of snapshot

- octoprint_nanny/workers/monitoring.py
Closes https://github.com/bitsy-ai/octoprint-nanny-webapp/issues/82
> Send raw image bytes over Print Nanny websocket

- octoprint_nanny/workers/monitoring.py
> Fix ImportError in main/slim package

- octoprint_nanny/predictor.py
Closes https://github.com/bitsy-ai/octoprint-nanny-plugin/issues/161
> Fix AttributeError not-editable source distribution

- .github/workflows/offline.yml
- .github/workflows/online.yml
- octoprint_nanny/plugins.py
- octoprint_nanny/static/js/nanny.js
- octoprint_nanny/templates/octoprint_nanny_settings_shared.jinja2
> Handle remote printer deletion

- Makefile
- octoprint_nanny/clients/mqtt.py
- octoprint_nanny/clients/rest.py
- octoprint_nanny/manager.py
- octoprint_nanny/plugins.py
- octoprint_nanny/settings.py
- octoprint_nanny/static/js/nanny.js
- octoprint_nanny/templates/octoprint_nanny_navbar.jinja2
- octoprint_nanny/templates/octoprint_nanny_tab.jinja2
- octoprint_nanny/types.py
- octoprint_nanny/workers/mqtt.py
- setup.py
- tests/test_manager.py
> Implement connection test for REST API & MQTT bridge

- .github/workflows/test.yml
- octoprint_nanny/__init__.py
- octoprint_nanny/clients/honeycomb.py
- octoprint_nanny/clients/mqtt.py
- octoprint_nanny/clients/rest.py
- octoprint_nanny/manager.py
- octoprint_nanny/workers/mqtt.py
- requirements.txt
- setup.cfg
- setup.py
- tests/workers/test_mqtt_worker.py
* add additional Honeycomb trace context to mqtt worker
* bump print-nanny-client version
> Release v0.7.5

- octoprint_nanny/plugins.py
- octoprint_nanny/workers/mqtt.py
Support both alpha and beta pong event strings
> Register connect_test_mqtt_pong event string and handler

- Makefile
> Rebuild printnanny-cli before starting local dev OctoPrint server

- Local.j2
- Makefile
- octoprint_nanny/events.py
- octoprint_nanny/plugins.py
- octoprint_nanny/static/js/nanny.js
- octoprint_nanny/templates/octoprint_nanny_settings_shared.jinja2
- octoprint_nanny/utils/printnanny_os.py
- setup.py
- tests/fixtures/os-release
- tests/test_events.py
- tests/utils/test_printnanny_os.py
* Rename OctoPrintInstall -> OctoPrintServer to match other server editions
* Also fix event pub/sub development setup
> Fix print progress event condition

- setup.py
closes https://github.com/bitsy-ai/printnanny-os/issues/63
> upgrade OctoPrint to 1.8.2

- octoprint_nanny/events.py
- octoprint_nanny/plugins.py
- octoprint_nanny/templates/octoprint_nanny_navbar.jinja2
- octoprint_nanny/templates/octoprint_nanny_unsupported_os.jinja2
- octoprint_nanny/utils/printnanny_os.py
- setup.py
old version threw exceptions to main OctoPrint loop
> Simplify "Unsupported OS" messaging and display logic

- octoprint_nanny/templates/octoprint_nanny_navbar.jinja2
- octoprint_nanny/templates/octoprint_nanny_settings_shared.jinja2
- octoprint_nanny/utils/printnanny_os.py
- setup.py
This variable is only set when PrintNanny OS is connected to a PrintNanny Cloud account.
> Fix requirement for plugin_octoprint_nanny_PRINTNANNY_PI to be set

- octoprint_nanny/events.py
- octoprint_nanny/plugins.py
- octoprint_nanny/static/js/octo_printnanny.js
- octoprint_nanny/templates/octoprint_nanny_wizard.jinja2
- octoprint_nanny/utils/printnanny_os.py
- requirements.txt
- setup.py
- tests/test_events.py
ref: https://github.com/bitsy-ai/printnanny-os/issues/131
> OctoPrint -> PrintNanny Cloud NATS event adapter

- octoprint_nanny/events.py
- requirements.txt
- setup.py
and some other deps flagged by the dependabot
ref: https://github.com/bitsy-ai/printnanny-os/issues/131
> bump printnanny-api-client to ~=0.116.0

- octoprint_nanny/plugins.py
- octoprint_nanny/utils/printnanny_os.py
- requirements.txt
- setup.py
- tests/test_events.py
- tests/utils/test_printnanny_os.py
closes: https://github.com/bitsy-ai/printnanny-os/issues/187
> Fix: OctoPrint settings / cloud data sync

- requirements.txt
- setup.py
- tests/test_events.py
ref: https://github.com/bitsy-ai/printnanny-os/issues/194
> Update printnanny-api-client to 0.121.0

- octoprint_nanny/events.py
- octoprint_nanny/utils/printnanny_os.py
ref: https://github.com/bitsy-ai/printnanny-os/issues/194
> Fix event loop
